### PR TITLE
Bugfix for #396

### PR DESCRIPTION
**Pull request by HuanhuanSunMSFT**
As dot is both IntelliSense trigger and committer, we need to treat it specially. For cd.., it doesn't meet actual desire when following regular rules. As a result, it needs to be treated as a special case. We may have more special cases in coming days.
@AndreSayreMSFT @EricMSFT @Microsoft/poshtools

### CODE REVIEW

**Comment by bmoore-msft** [comment]
dot should be an intellisense trigger only when preceded by a space, right?

**Comment by HuanhuanSunMSFT** [comment]
No, it can be IntelliSense trigger in many occasions such as preceded by a variable. In ISE, whenever typing a dot, you can see IntelliSense flashes in the status bar indicating it triggers IntelliSense but not showing any completion list as it returns an empty completion list. @bmoore-msft

**Comment by ASayre** [comment]
This is not a general case fix; eg:

``` powershell
function potato..{Write-Host "Potato";}
```

Type that into the REPL window, and try to use `potato..`

**Comment by bmoore-msft** [comment]
@HuanhuanSunMSFT - understood
@AndreSayreMSFT - why would I do that?

**Comment by ASayre** [comment]
@bmoore-msft : That's an example counter case.  Any arbitrary function can be defined in this manner, in the same way `cd..` is an arbitrary command/function.

**Comment by bmoore-msft** [comment]
Interesting...  though in your case it's part of a fn name, in the other it's a param.  Something tells me we haven't seen the last of this yet.

**Comment by ASayre** [comment]
@bmoore-msft No, it's not a param in the original case -- We want to differentiate between the command named `cd..` and the command `cd ..` which has `..` as a parameter.

**Comment by bmoore-msft** [comment]
how do you know which to use then?

**Comment by ASayre** [comment]
@bmoore-msft How do you know to use `cd` instead of `set-location` or `chdir` ? :)  It's just another way to do the same thing.

**Comment by bmoore-msft** [comment]
no, how do we know when to treat cd.. as a function instead of a command + param?

(we really have a set-location cmdlet???  is cd the alias :))

**Comment by HuanhuanSunMSFT** [comment]
This fix determine whether to commit the completion and then ignore user's input based on whether user's input is fully matched to the coming completion.
Also add another small feature: when user's input is case-sensitive matched to a completion, then we don't need to bring up the completion session. It has to be case-sensitive because it's quite often we don't care the case and just type name of a function, member, etc. Then with IntelliSense's help we can get right case, though PS is case-insensitive.
@bmoore-msft @AndreSayreMSFT

**Comment by ASayre** [comment]
"Also add another small feature: when user's input is case-sensitive matched to a completion, then we don't need to bring up the completion session." Example?

**Comment by HuanhuanSunMSFT** [comment]
If you type cd.. quickly, the second dot will trigger IntelliSense. The same with function named potato.. @AndreSayreMSFT

**Comment by ASayre** [comment]
but re the case sensitivity?

**Comment by bmoore-msft** [comment]
yeah I don't understand the case-sensitivity requirement - autocomplete should _not_ be case-senstive if that's what you meant...

**Comment by HuanhuanSunMSFT** [comment]
I require it case-sensitive cause sometimes people type without caring cases but expect to get it right through auto completion. E.g., you define a function called PotatoEggs.. , then you type potatoeggs.. and get the Intellisense, you may want to get cases right by just committing it. Though PowerShell is case-insensitive, we still want to keep names consistent, right?
@bmoore-msft @AndreSayreMSFT

**Comment by bmoore-msft** [comment]
Do you mean when we "Complete" something, we complete it with the proper casing? (this would be fine) Or in order to find a match, we "require" the proper casing? (not so good)

In general we want to keep behavior similar to ISE to minimize the learning curve / switching costs for folks using both.

**Comment by ASayre** [comment]
I think I understand now; looks good

**Comment by HuanhuanSunMSFT** [comment]
@bmoore-msft 
I mean the former one. We can complete something with proper casing. Sure we cannot require the proper casing to find a match.

**Pull request merged**
