### PR TITLE
Split manifest/builds for different visual studio versions

### PR DESCRIPTION
**Pull request by ASayre**
@HuanhuanSunMSFT @adamdriscoll @Microsoft/poshtools 

This change DOES remove the ability for the old VSIX to install on Dev14, so before we push up to the Gallery, we'll need to have the Dev14 one up as well.

### CODE REVIEW

**Comment by HuanhuanSunMSFT** [comment]
Looks good. A follow up is we need to verify this works on build-to-build with old VSIX's.

**Comment by ASayre** [comment]
thanks!  in some of my own SxS testing, I just identified an issue, so working through that issue before submitting.

**Comment by ASayre** [comment]
@HuanhuanSunMSFT Presuming CTI is all good, did you want to take another look?

**Comment by HuanhuanSunMSFT** [comment]
Looks good. I'll let CTI do more tests around this to make sure good enough.

**Comment by ASayre** [comment]
CTI says this looks good :)

**Pull request merged**
