### PR TITLE
Add the function of triggering the auto completion by Ctrl+Space

### PR DESCRIPTION
**Pull request by HuanhuanSunMSFT**
This is for #9 @AndreSayreMSFT @bilalwMSFT @adamdriscoll @jinglou- @EricMSFT

### CODE REVIEW

**Comment by HuanhuanSunMSFT** [comment]
Ignore the other 3 commits

**Comment by ASayre** [comment]
@HuanhuanSunMSFT 
- Does this need to trigger in the REPL Window w/regards to completion? PTVS's Repl has Ctrl-space working for example.  [However, the Completion Command isn't sent for PS's repl window when that happens.  Is PTVS doing something funny?]
- This doesn't automatically select the first item.  Eg, can't "Ctrl-Space; Enter" like in ISE and other VS languages
- Deletion of test doesn't re-filter when Ctrl-Space originally triggers the Intellisense

**Comment by HuanhuanSunMSFT** [comment]
@AndreSayreMSFT  
Good catch. I haven't consider REPL window for this. Consider this one as a initial step. 

As for automatic selection, Poshtool doesn't have this function now. If you type '-' or '$', you'll see no item is selected. 
The same for your last point. Ctrl+Space triggers the IntelliSense the same way as other set of chars, there are not any difference after the trigger happens. E.g., if you type '-' or '$' and delete it, there will be no re-filter.

We may open an issue for the two points above.

**Comment by ASayre** [comment]
Re: Automatic selection and refiltering -- We see it when we start filtering/typing:  Eg, "Get-a"...

For example, Type 'Get-Al', having intellisense come up after the dash and type/backspace from there.  However, dismiss that Intellisense and then trigger completion upon the partial string, and you'll see the issues above.

**Comment by HuanhuanSunMSFT** [comment]
@AndreSayreMSFT  
I agree. I mean if you keep typing then you'll see auto-selection and refiltering. But Ctrl+Space as well as any other trigger chars won't do this. So we can consider it as a bug or as feature unsupported yet.

**Pull request merged**
